### ISSUE TITLE
Yarn install failed in node 16.17+

### ISSUE THREAD

**Issue by Mengchenchen** [kubeclipper/console#156]
**Describe the Bug**
Yarn install failed in the e2e test 

For UI issues please also add a screenshot that shows the issue.
![yarn](https://user-images.githubusercontent.com/100403985/188848571-0b6680a5-0bf9-45b5-837b-fdc1893e5885.png)

the node version is too high

**Comment by moweiwei** [comment]
antd-scss-theme-plugin dependence node-sass,  but node 16+ not support node-sass 
suggest remove antd-scss-theme-plugin

**Comment by moweiwei** [comment]
close
