### ISSUE TITLE
clutsre upgrade version check error

### ISSUE THREAD

**Issue by Xvv-v** [kubeclipper/console#295]
**Describe the Bug**
![企业微信截图_8c0223af-6812-40bb-9509-6b41d5943bef](https://user-images.githubusercontent.com/55474221/204223192-c4abf36e-a388-4c9e-b36c-1d3b6175d2f0.png)

**Versions Used**
Kubernetes: v1.18.20, v1.19.16
Kubeclipper: v1.3.1

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters: 8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

1. create a cluster
2. do upgrade operation
3. see error

**Expected behavior**

**Comment by moweiwei** [comment]
https://github.com/kubeclipper/console/pull/314
